import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1400, height: 1000 } });
await p.goto('http://localhost:8080/fpl-players-analysis.html', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(4500);
await p.evaluate(() => document.querySelector('.tab[data-position="ROUTES"]').click());
await p.waitForTimeout(1200);
await p.evaluate(() => window.scrollTo(0, 0));
await p.waitForTimeout(300);
await p.screenshot({ path: 'routes.png' });
console.log('shot taken');
await b.close();
