#!/usr/bin/env node
/* The Open Graph and Twitter block on every shareable page.
 *
 * It was on five pages, and none of the five named an image — so a link to
 * any page of this site pasted into a WhatsApp group, a Reddit thread or a
 * Discord server, which is where FPL is actually discussed, rendered as a
 * bare line of blue text. That is the site's only appearance in front of
 * people who have not chosen to visit it.
 *
 * Written here rather than by hand because the block restates three things
 * the page already says — its title, its description and its canonical URL —
 * and three copies of a fact rot apart. Generated from the page itself, so
 * changing the <title> and re-running is the whole procedure.
 *
 * Usage:  node tools/social-meta.mjs [--check]
 *         --check writes nothing and fails if any page's block is missing or
 *         has drifted from what this would generate, for CI.
 */
import fs from 'node:fs';
import { cardPages } from './make-og-cards.mjs';

const SITE = 'https://easyfpl.com';
const check = process.argv.includes('--check');
const OPEN = '<!-- Social card: generated by tools/social-meta.mjs from this page\'s own';
const CLOSE = '<!-- /social card -->';

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function block({ slug, title, desc }, canonical) {
    const t = title.split(/\s+\|\s+/)[0].trim();
    const img = `${SITE}/assets/og/${slug}.png`;
    return `    ${OPEN}
         title, description and canonical URL. Do not edit by hand; re-run it.
         The image is drawn by tools/make-og-cards.mjs from the same three. -->
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="EasyFPL">
    <meta property="og:locale" content="en_GB">
    <meta property="og:title" content="${esc(t)}">
    <meta property="og:description" content="${esc(desc)}">
    <meta property="og:url" content="${canonical}">
    <meta property="og:image" content="${img}">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:image:alt" content="${esc(t)} — EasyFPL">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${esc(t)}">
    <meta name="twitter:description" content="${esc(desc)}">
    <meta name="twitter:image" content="${img}">
    ${CLOSE}
`;
}

const problems = [];
let written = 0;

for (const p of cardPages()) {
    let html = fs.readFileSync(p.file, 'utf8');
    const canon = (html.match(/<link rel="canonical" href="([^"]+)"/) || [])[1];
    if (!canon) { problems.push(`${p.file}: no canonical to build a social card URL from`); continue; }

    /* Anything already there comes out first, comment block and loose tags
       alike — five pages carried a partial hand-written set, and appending to
       those would have given them two og:title each. */
    let stripped = html.replace(new RegExp(`[ \\t]*${OPEN.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&')}[\\s\\S]*?${CLOSE}\\n`, 'g'), '');
    stripped = stripped.replace(/[ \t]*<meta (?:property="og:|name="twitter:)[^>]*>\n/g, '');

    const m = /^([ \t]*)<link rel="canonical"[^>]*>\n/m.exec(stripped);
    if (!m) { problems.push(`${p.file}: canonical vanished while rewriting`); continue; }
    const next = stripped.slice(0, m.index + m[0].length) + block(p, canon) + stripped.slice(m.index + m[0].length);

    if (next === html) continue;
    if (check) problems.push(`${p.file}: social card block is missing or out of date`);
    else { fs.writeFileSync(p.file, next); written++; }
}

if (problems.length) {
    for (const x of problems) console.error(`✗ ${x}`);
    console.error('\nRun: node tools/social-meta.mjs');
    process.exit(1);
}
console.log(check
    ? `✓ every shareable page's social card block matches its title, description and canonical`
    : `✓ social card block written into ${written} page(s)`);
